### ISSUE TITLE
Skip to the content. を削除する

### ISSUE THREAD

**Issue by takasehideki** [algyan/algyan.github.io#2]
一番上に `Skip to the content.` と出ている．ヘッダを飛ばせる．
必要無さそうなので，削除したい．

**Comment by shoko93** [comment]
自分のレポジトリの方で削除してみました。

https://shoko93.github.io/algyan.github.io/

プルリク送ってもいいでしょうか？

**Comment by takasehideki** [comment]
はい，ぜひお送りください！
