### ISSUE TITLE
GitHubマークの解像度を上げる

### ISSUE THREAD

**Issue by takasehideki** [algyan/algyan.github.io#4]
GitHubのロゴマークがギザギザしている．
公式ページからダウンロードできる `GitHub-Mark-120px-plus.png` を持ってきている．
https://github.com/logos

あまり綺麗ではないので綺麗なものに変えたい．いろいろ権利周りには注意しないといけない．

![image](https://user-images.githubusercontent.com/23649012/86224154-7a1d9f80-bbc3-11ea-9943-faab0311ed50.png)

**Comment by keni-n** [comment]
EPSからconvertで変換して、切り出せば大丈夫かと。dimensionを変えるなとありますね。
![GitHub-Mark-740](https://user-images.githubusercontent.com/5704706/86529038-5bcbe280-bee8-11ea-9cb9-9a35576cd7b4.png)

**Comment by takasehideki** [comment]
@keni-n さん，ありがとうございます！
中のヒトはepsからconvertする方法もぱっと分からないデザイン力なので，とっても助かります！！
#158 のPull Requestを作成し，取り込ませていただきました〜
