### ISSUE TITLE
Twitterフィードを追加する

### ISSUE THREAD

**Issue by takasehideki** [algyan/algyan.github.io#5]
Twitterの公式アカウントのフィードがあると良いかも？

**Comment by shoko93** [comment]
こんな感じでしょうか？
https://shoko93.github.io/algyan.github.io/test2.html

**Comment by takasehideki** [comment]
@shoko93 あざっす！
ちょっと長くなってしまってスクロール量が多くなるのがネックですねぇ，，，
なんかしら見栄え良くしたいところです（あんまりいいアイデアはありません^^;
- SNSの紹介順を Facebook -> GitHub -> Twitter にして，その後ろにTimelineを掲載する
- frameのウインドウを小さくする

**Comment by shoko93** [comment]
@takasehideki 

高さと表示順を調整してみました。

https://shoko93.github.io/algyan.github.io/test2.html

実際のところ↓のURLで生成できるiframeを貼り付けてるだけです。今高さを500pxにしてます。
https://publish.twitter.com/#

**Comment by takasehideki** [comment]
高さ600px, 幅400px くらいがちょうど良いですかね？
それでPull Requestいただけましたら幸いです！！

**Comment by takasehideki** [comment]
これはMergeされたのをすっかり放置していたので，Closeとします．あざまっした！！
