### ISSUE TITLE
connpassのイベントページと連携？

### ISSUE THREAD

**Issue by takasehideki** [algyan/algyan.github.io#6]
connpassからよいAPIが提供されていれば，それを使って今後開催のイベント情報とリンクを掲載できると良さそう．

**Comment by shoko93** [comment]
[connpass API](https://connpass.com/about/api/)

こんな感じでALGYANのイベントを引っ張ってくることができます。
https://connpass.com/api/v1/event/?series_id=1561

今のTOPページのどこかに適当に設置してみてよければ組み込んでみましょうか？

**Comment by takasehideki** [comment]
おぉ，やはりその手のAPIは提供されているのですね．
こんな感じでできそう！てのがあったら，ぜひ組み込んで見せてください！

全てとなると大変なので，できれば今後の開催予定のイベントのみ羅列できると良いかなと思っています．でも動的ページ生成になるかな？それはJS組まないとけっこう難しいのかな？とか思っています．要するに，あんまり分かっていませんｗ

**Comment by shoko93** [comment]
テストページ作って組み込んでみました。

https://shoko93.github.io/algyan.github.io/test.html

JSでAPIからデータ取ってきてます。

**Comment by takasehideki** [comment]
おぉ素晴らしいです！私のイメージ通りです！！😄 
@atkogure さん，どうでしょうか？

**Comment by atkogure** [comment]
すす素晴らしすぎます！

**Comment by atkogure** [comment]
（なるほどこうやってコミュニケーションするんですね！）

**Comment by takasehideki** [comment]
@atkogure はい，こんな感じでコミュニケーションしていきます〜
@shoko93 では追加しましょう！Pull Requestお願いします〜
